name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jacobarthurs/shipbin@v0
        with:
          registry: npm
          name: mytestcli1234321
          org: 98c09f9d-8bc1-4733-96db-5850e4c6a040
          provenance: false
          artifacts: |
            linux/amd64:./dist/mytestcli1234321_linux_amd64_v1/mytestcli1234321
            linux/arm64:./dist/mytestcli1234321_linux_arm64/mytestcli1234321
            darwin/amd64:./dist/mytestcli1234321_darwin_amd64_v1/mytestcli1234321
            darwin/arm64:./dist/mytestcli1234321_darwin_arm64/mytestcli1234321
            windows/amd64:./dist/mytestcli1234321_windows_amd64_v1/mytestcli1234321.exe
            windows/arm64:./dist/mytestcli1234321_windows_arm64/mytestcli1234321.exe
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: jacobarthurs/shipbin@v0
        with:
          registry: pypi
          name: mytestcli1234321
          artifacts: |
            linux/amd64:./dist/mytestcli1234321_linux_amd64_v1/mytestcli1234321
            linux/arm64:./dist/mytestcli1234321_linux_arm64/mytestcli1234321
            darwin/amd64:./dist/mytestcli1234321_darwin_amd64_v1/mytestcli1234321
            darwin/arm64:./dist/mytestcli1234321_darwin_arm64/mytestcli1234321
            windows/amd64:./dist/mytestcli1234321_windows_amd64_v1/mytestcli1234321.exe
            windows/arm64:./dist/mytestcli1234321_windows_arm64/mytestcli1234321.exe
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      - name: Update Go module proxy
        run: GOPROXY=https://proxy.golang.org go list -m github.com/jacobarthurs/mytestcli1234321@${GITHUB_REF_NAME}
      - name: Update floating major tag
        run: |
          MAJOR=$(echo "${GITHUB_REF_NAME}" | cut -d. -f1)
          git tag -f "${MAJOR}"
          git push origin "${MAJOR}" --force