name: Test Darwin

on:
  workflow_dispatch:

jobs:
  npm-arm64:
    runs-on: macos-latest
    steps:
      - name: Test npm darwin/arm64
        run: |
          npm install -g mytestcli1234321
          mytestcli1234321 --version

  npm-amd64:
    runs-on: macos-latest
    steps:
      - name: Test npm darwin/amd64 (Rosetta)
        run: |
          arch -x86_64 npm install -g mytestcli1234321
          arch -x86_64 mytestcli1234321 --version

  pypi-arm64:
    runs-on: macos-latest
    steps:
      - name: Test PyPI darwin/arm64
        run: |
          pip3 install --break-system-packages mytestcli1234321
          mytestcli1234321 --version

  pypi-amd64:
    runs-on: macos-latest
    steps:
      - name: Test PyPI darwin/amd64 (Rosetta)
        run: |
          pip3 download --platform macosx_10_12_x86_64 --only-binary :all: --no-deps -d /tmp/wheel mytestcli1234321
          cd /tmp/wheel && unzip -q *.whl
          arch -x86_64 */bin/mytestcli1234321 --version
